project:
  type: website
  output-dir: docs
  resources:
    - "data/*.mp3"
    - "data/LibriSpeech/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"

lang: ko
date-format: "YYYY년 MM월 DD일"

website:
  title: "chatGPT"
  site-url: https://r2bit.com/konkuk/
  page-navigation: true
  reader-mode: true
  favicon: "images/konkuk/favicon/android-chrome-512x512.png"
  google-analytics: "UA-229551680-1"
  search:
    location: navbar
    type: overlay
  navbar:
    search: true
    background: light
    collapse-below: lg
    type: light
    logo: "images/konkuk/favicon_circle/android-chrome-512x512.png"
    left:
      - text: "커리큐럼"
        menu:
        - href: chatGPT_setup.qmd
          text: "1주차: 환경설정"
        - href: chatGPT_chatGPT.qmd
          text: "ㄴ 챗GPT(ChatGPT)"
        - href: chatGPT_setup_bash.qmd
          text: "ㄴ 배쉬(Bash)"
        - href: chatGPT_setup_sql.qmd
          text: "ㄴ 데이터베이스(SQL)"
        - href: chatGPT_setup_python.qmd
          text: "ㄴ 파이썬(Python)"
        - href: chatGPT_setup_R.qmd
          text: "ㄴ R"
        - text: "----------------"
        - href: markdown.qmd
          text: "2주차: 마크다운"
        - href: api_programming.qmd
          text: "3주차: API 프로그래밍"

    right:
      - icon: github
        href: https://github.com/bit2r/chatGPT
      - href: https://r2bit.com
        text: "R사용자회"
      - icon: github
        text: "RTutor"
        href: https://rtutor.ai/
      - text: "About"
        href: about.qmd
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/chatGPT)
    background: "#2780e3"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/quarto.scss
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true


bibliography: bibliography.bib
csl: apa-single-spaced.csl
link-citations: true

execute:
  freeze: true
